import type { Metadata } from "next";
// Fonts
import { Geist, Geist_Mono } from "next/font/google";
// Provider
import ThemeProvider from "@/providers/ThemeProvider";
import QueryProvider from "@/providers/QueryProvider";
import ShopProvider from "@/providers/ShopProvider";

import "../css/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <ThemeProvider>
            <ShopProvider>{children}</ShopProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
